openai: "3.0.0"
info:
  title: "Hello API"
  version: "0.1.0"
servers:
  - url: "https://api.example.edu/api/v1"
    description: "Production"
paths:
  /health:
    get:
      summary: "Health check"
      description: "服務是否正常"
      security: []
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: "OK" }
